### ISSUE TITLE
Can't filter & sort column with enum type

### ISSUE THREAD

**Issue by Vija02** [ultorg/public_issues#17]
Example of enum:
```sql
create type status as enum ('PENDING', 'DONE');
```

Here's the error message on filter:
```
(generated query): Query execution problem (backend said 'ERROR: collations are not supported by type .... Position: 46')
```

**Comment by eirikbakke** [comment]
Which database backend is this on?

A workaround is to insert a formula field (Insert Calculated Field Before) and enter `=TEXT([NameOfYourEnumColumn])`. Then you can filter on the calculated field instead.

**Comment by Vija02** [comment]
I'm using PostgreSQL

**Comment by eirikbakke** [comment]
Thanks!

**Comment by eirikbakke** [comment]
The fix for this PostgreSQL issue will be in the next Ultorg release; thank you for reporting!

Tables with enums are now also part of the automated tests that run before each Ultorg releases.

On MySQL, enums seemed to work already, but I added some extra code to the MySQL dialect handler to cast them to CHAR e.g. before using them in an ORDER BY clause (to ensure alphabetic rather than index order). Oracle, Microsoft SQL Server, SQLite, and Presto/Athena do not have a dedicated enum type, and so are not affected.

**Comment by eirikbakke** [comment]
Hi, Michael. There's a new Ultorg release up now, at the old download link, which fixes this bug.

Thanks for reporting!
