### ISSUE TITLE
Selection List (dropdown menu when editing foreign key values)

### ISSUE THREAD

**Issue by bdillahu** [ultorg/public_issues#19]
When editing data, have the ability to have a "lookup table" with data to have a selection/dropdown list to fill data - which then keeps foreign keys, etc. straight.

I'm not sure I'm explaining that well.

**Comment by eirikbakke** [comment]
That's planned, once the other editing features get a little more robust. The plan is to make "collapsed join" cells (illustrated in https://github.com/ultorg/public_issues/issues/4 ) show a dropdown when edited, so that you can set e.g. an "Instructor ID" field by picking from a list of First Name+Last Name values from the foreign table.

**Comment by eirikbakke** [comment]
A mockup of how this might work in the future is shown here:

![Dropdown Mockup](https://user-images.githubusercontent.com/886243/167275608-cd606bd3-0a5e-4dd3-92c1-d6648b5fd96f.png)

**Comment by bdillahu** [comment]
Just what I was thinking… thanks!

**Comment by eirikbakke** [comment]
Dropdown lists for data editing is now implemented! (In Ultorg 1.2.2 and with various adjustments in Ultorg 1.2.3 and 1.2.4).

![editCompletion](https://user-images.githubusercontent.com/886243/198356202-4f2ae830-b453-460b-b611-78ac0f79262c.png)

See the release notes for Ultorg 1.2.2 at https://www.ultorg.com/releasenotes/ . Basically, the dropdown list appears whenever you are editing a column that has a join against another table's primary key. This join could come from either a foreign key relationship or a join manually added via the Custom Group action. The dropdown list feature also interacts properly with the Compact Join feature (from Ultorg 1.0.9), so that a selection from the referenced table will also be shown next to the actual primary key value.

A dropdown list is also shown when editing general text columns, in this case showing existing values in the same column, as an aid for entering new values. This is similar to how e.g. Excel sometimes works when editing a cell in a table containing many values:

![editCompletionSearch](https://user-images.githubusercontent.com/886243/198356608-c2fa80d3-3269-4b49-b975-404b2e038a88.png)

Existing Ultorg users can find the latest version at the old download link. Thanks for this feature request!
