### ISSUE TITLE
Filter column to show non-null values

### ISSUE THREAD

**Issue by moorbrook** [ultorg/public_issues#28]
I have a sparse CSV file.  Like this: 

![CleanShot 2022-06-24 at 11 18 59](https://user-images.githubusercontent.com/619/175627553-59bfc57e-6d5d-4109-b963-480cc8f82b94.png)

Any one know how to filter the column to only show non null values?

Thanks!

**Comment by eirikbakke** [comment]
Yes! In the Filter popup, if you click the "(Include All)" row first, like you have done in the screenshot, you can now click the "null" row to exclude the null values.

(The filter has two modes, which you can toggle with the "(Include All)" row. By default, it includes only the values you click. But if you click "(Include All)", so that all checkboxes become checked, you can then click values to _exclude_ instead.)

**Comment by moorbrook** [comment]
Thank you.
Keep thinking along the line of how to type in 'is not null' into the text field.
