### ISSUE TITLE
feature: column level format option of "significant digits" for numerics (default to 2), and scientific notation display 

### ISSUE THREAD

**Issue by malcook** [ultorg/public_issues#29]
Much of my data is very small floats that are best displayed in scientific notation with 2 or 3 significant digits.

e.g. 2E-15 (or 0.000000000000005)

Currently anything less than 0.01 by default displays as "0"

My use cases tend toward scientific analysis results.  There are tiny "p-values" are everywhere!

Having control over significant digits and a reasonable default would be a real win, and configurable threshold for triggering scientific notation, possibly taking inspiration from [Excel uses scientific format automatically for large and small numbers of 12 digit values or more](https://www.wallstreetmojo.com/scientific-notation-in-excel/)

**Comment by eirikbakke** [comment]
There are two icons in the toolbar which lets you adjust the numeric precision, for whichever column the blue cursor is corrently located in:

<img width="66" alt="precision" src="https://user-images.githubusercontent.com/886243/175784790-0bc009c8-087b-4843-986e-952b3db1e4ba.png">

(The toolbar icons are a shortcut to the "Decimal Places" setting that you can also find under the "Format" option in the column dropdown menu.)

Would you still prefer scientific notation in this case, rather than increasing the number of decimals shown?

Adding an option to enable scientific notation would be easy, but I'd have to decide whether there should be an exponent threshold like in Excel, or whether all numbers in a column should be displayed in the same way (for ease of comparison).

**Comment by malcook** [comment]
Having option to display in scientific notation is what I would like, with control over the number of significant digits to show, defaulting to 2.

re: "whether there should be an exponent threshold like in Excel, or whether all numbers in a column should be displayed in the same way (for ease of comparison)" - I'd prefer the 2nd - I never liked Excel's defaulting to mixing formats.  Perhaps others would prefer the first, in which case you might have a preference and have the default exponenent threshold be infinite, which could be set to 12 to get Excel-like behavior.   ( /bike-shedding)

**Comment by eirikbakke** [comment]
A "scientific notation" formatting option is now available in Ultorg 1.2.9, implementing this suggestion.

![scientificNotation](https://github.com/ultorg/public_issues/assets/886243/eaa1300e-bf27-4832-b654-69f1e7a1c786)

I've pointed all the existing download links to the latest Ultorg version now; complete release notes are at https://www.ultorg.com/releasenotes/
