### ISSUE TITLE
how to refresh db schema?

### ISSUE THREAD

**Issue by wizzard0** [ultorg/public_issues#58]
right now I'm restarting Ultorg so it would redetect the schema, but I really miss the "refresh schema" from DataGrip

Manual query console would also be great (in particular, to define custom columns on fields extracted from JSON)

**Comment by eirikbakke** [comment]
If you right-click the data source in the Folders pane, there's a "Refresh Table Metadata" action which should reload the list of tables, columns etc.

For database connections (e.g. PostgreSQL), this will also briefly disconnect and reconnect the connection so that cached permissions and such are refreshed.

<img width="258" alt="refresh" src="https://github.com/ultorg/public_issues/assets/886243/91a4683f-71ee-4dcd-b203-f1b8acf2080f">

What's the "define custom columns on fields extracted from JSON" use case you mentioned? Could you give an example?

**Comment by eirikbakke** [comment]
There's a new Ultorg version available now, which exposes the Refresh Table Metadata action in the main menu (under the "Data" menu). This should make it more discoverable.

![Untitled](https://github.com/ultorg/public_issues/assets/886243/96164a81-cccd-470b-be40-d83399c2266f)

As for extracting fields from JSON data, there was actually a feature added in Ultorg 1.2.9 for this purpose:

![expandJSONfields](https://github.com/ultorg/public_issues/assets/886243/27cbaec3-3885-44a0-a3b6-a4270b0f70f4)

The latest Ultorg version is available at https://www.ultorg.com/download/ , with all trial periods having been reset for this release. See the [Release Notes](https://www.ultorg.com/releasenotes/) for a full list of improvements.
