### ISSUE TITLE
How to connect to AWS Athena

### ISSUE THREAD

**Issue by slifin** [ultorg/public_issues#62]
Hi, my current setup with Datagrip is something like this:

<img width="1191" alt="Screenshot 2023-11-14 at 13 17 36" src="https://github.com/ultorg/public_issues/assets/198857/6a34d668-8879-4f4f-b19b-a6cf15e9cc25">

Does Ultorg have support for Athena?

**Comment by slifin** [comment]
ok so far I've added the driver AthenaJDBC42-2.1.1.1001.jar

I'm guessing what the inputs need to be to connect, but nearly every time I get this error:

<img width="617" alt="Screenshot 2023-11-14 at 13 52 38" src="https://github.com/ultorg/public_issues/assets/198857/dafdac4d-06bc-4964-b96c-0ff189723030">

I don't really have enough feedback to tell what's wrong beyond not being able to init a ClientConfiguration class

**Comment by eirikbakke** [comment]
When you say "nearly every time", I assume this is because you have been trying different parameters and only some of them produce the error message?

Could you click "Application Log" in the "Internals" menu and see if there are more details relating to the error message there?

**Comment by eirikbakke** [comment]
I tried connecting to Amazon Athena today, and while I didn't get exactly the same error, it seems necessary to use the "JDBC driver with AWS SDK" (AthenaJDBC42-2.1.1.1000.jar) version of the driver rather than the "JDBC driver without AWS SDK" (AthenaJDBC42-2.1.1.1001.jar).

(In my case I was authenticating with an IAM access key ID and secret access key, which become the "username" and "password" in the connection dialog box, respectively. Though I see the word "SAML" in your DataGrip screenshot, which suggests you might be using a different kind of authentication.)

**Comment by slifin** [comment]
Yep this was the issue, thank you!

For my auth I had to do jdbc:awsathena://AwsRegion=eu-west-1;Profile=default

And leave username/password blank

`default` is the name of my credentials in ~/.aws/credentials which also includes a aws_session_token because of 2fa (I think?)

**Comment by eirikbakke** [comment]
Ah, great! I'll incorporate your observations into Ultorg's documentation (which I'm in the process of improving).
